version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fakeshop-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fakeshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fakeshop-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fakeshop-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=fakeshop
      - FAKESTORE_API_URL=https://fakestoreapi.com
    depends_on:
      - postgres
    networks:
      - fakeshop-network

networks:
  fakeshop-network:
    driver: bridge

volumes:
  postgres_data: